#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Meta/WitAi/Requests/AudioStreamHandler.hpp"
#include "Meta/WitAi/Requests/IVRequestDownloadDecoder.hpp"
#include "Meta/WitAi/Requests/TextStreamHandler.hpp"
#include "Meta/WitAi/Requests/VRequest.hpp"
#include "Meta/WitAi/Requests/VRequestDecodeDelegate_1.hpp"
#include "Meta/WitAi/Requests/VRequestMethod.hpp"
#include "Meta/WitAi/Requests/VRequestProgressDelegate.hpp"
#include "Meta/WitAi/Requests/VRequestResponseDelegate.hpp"
#include "Meta/WitAi/Requests/VRequestResponse_1.hpp"
#include "Meta/WitAi/Requests/VRequest__DecodeFileHeaders_d__110.hpp"
#include "Meta/WitAi/Requests/VRequest__DecodeFile_d__112.hpp"
#include "Meta/WitAi/Requests/VRequest__DecodeText_d__121.hpp"
#include "Meta/WitAi/Requests/VRequest__GetDownloadedText_d__104.hpp"
#include "Meta/WitAi/Requests/VRequest__GetError_d__103.hpp"
#include "Meta/WitAi/Requests/VRequest__RequestFileDownload_d__113.hpp"
#include "Meta/WitAi/Requests/VRequest__RequestFileExists_d__116.hpp"
#include "Meta/WitAi/Requests/VRequest__RequestFileHeaders_d__109.hpp"
#include "Meta/WitAi/Requests/VRequest__RequestFile_d__111.hpp"
#include "Meta/WitAi/Requests/VRequest__RequestJsonGet_d__124_1.hpp"
#include "Meta/WitAi/Requests/VRequest__RequestJsonPost_d__125_1.hpp"
#include "Meta/WitAi/Requests/VRequest__RequestJsonPost_d__126_1.hpp"
#include "Meta/WitAi/Requests/VRequest__RequestJsonPost_d__127_1.hpp"
#include "Meta/WitAi/Requests/VRequest__RequestJson_d__122_1.hpp"
#include "Meta/WitAi/Requests/VRequest__RequestText_d__120.hpp"
#include "Meta/WitAi/Requests/VRequest__Request_d__92_1.hpp"
#include "Meta/WitAi/Requests/VRequest__WaitForTimeout_d__97.hpp"
#include "Meta/WitAi/Requests/VRequest__WaitForTurn_d__5.hpp"
#include "Meta/WitAi/Requests/VRequest__WaitWhileRunning_d__102.hpp"
#include "Meta/WitAi/Requests/VoiceErrorSimulationType.hpp"
#include "Meta/WitAi/Requests/VoiceServiceRequest.hpp"
#include "Meta/WitAi/Requests/VoiceServiceRequestEvent.hpp"
#include "Meta/WitAi/Requests/VoiceServiceRequestEvents.hpp"
#include "Meta/WitAi/Requests/VoiceServiceRequestOptions.hpp"
#include "Meta/WitAi/Requests/VoiceServiceRequestResults.hpp"
#include "Meta/WitAi/Requests/VoiceServiceRequest__SimulateResponse_d__10.hpp"
#include "Meta/WitAi/Requests/WitAudioRequestOption.hpp"
#include "Meta/WitAi/Requests/WitMessageVRequest.hpp"
#include "Meta/WitAi/Requests/WitResponseDecoder.hpp"
#include "Meta/WitAi/Requests/WitSocketRequest.hpp"
#include "Meta/WitAi/Requests/WitTTSVRequest.hpp"
#include "Meta/WitAi/Requests/WitTTSVRequest__RequestDownload_d__25.hpp"
#include "Meta/WitAi/Requests/WitTTSVRequest__RequestStreamFromDisk_d__23.hpp"
#include "Meta/WitAi/Requests/WitTTSVRequest__RequestStream_d__24.hpp"
#include "Meta/WitAi/Requests/WitTTSVRequest__SetupTts_d__26.hpp"
#include "Meta/WitAi/Requests/WitUnityRequest.hpp"
#include "Meta/WitAi/Requests/WitUnityRequest_<>c__DisplayClass19_0___HandleSend_b__0_d.hpp"
#include "Meta/WitAi/Requests/WitUnityRequest__SendMessageAsync_d__20.hpp"
#include "Meta/WitAi/Requests/WitVRequest.hpp"
#include "Meta/WitAi/Requests/WitVRequest__RequestWitGet_d__22_1.hpp"
#include "Meta/WitAi/Requests/WitVRequest__RequestWitPost_d__23_1.hpp"
#include "Meta/WitAi/Requests/WitVRequest__Request_d__21_1.hpp"
#ifdef __cpp_modules
                    export module Requests;
                    #endif
                
