#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Modio/Error.hpp"
#include "Modio/IModioLogHandler.hpp"
#include "Modio/IModioServiceSettings.hpp"
#include "Modio/LinkType.hpp"
#include "Modio/LogLevel.hpp"
#include "Modio/ModIndex.hpp"
#include "Modio/ModIndex__CreateIndexFromScan_d__7.hpp"
#include "Modio/ModIndex__RefreshIndexModObjects_d__16.hpp"
#include "Modio/ModIndex__UpdateIndexForMod_d__9.hpp"
#include "Modio/ModIndex__UpdateIndexWithMissingEntriesFromScan_d__8.hpp"
#include "Modio/ModInstallationManagement.hpp"
#include "Modio/ModInstallationManagement_DownloadAndExtractJob__Run_d__3.hpp"
#include "Modio/ModInstallationManagement_DownloadJob__Run_d__1.hpp"
#include "Modio/ModInstallationManagement_InstallJob__Run_d__2.hpp"
#include "Modio/ModInstallationManagement_OperationPhase.hpp"
#include "Modio/ModInstallationManagement_OperationType.hpp"
#include "Modio/ModInstallationManagement_ScanForInstalledModJob__Run_d__1.hpp"
#include "Modio/ModInstallationManagement_ScanMissingInstallsJob__Run_d__1.hpp"
#include "Modio/ModInstallationManagement_UninstallJob__Run_d__1.hpp"
#include "Modio/ModInstallationManagement_ValidateJob__Run_d__1.hpp"
#include "Modio/ModInstallationManagement__AddTemporaryMods_d__44.hpp"
#include "Modio/ModInstallationManagement__DownloadAndInstallMod_d__53.hpp"
#include "Modio/ModInstallationManagement__EnqueueJobs_d__41.hpp"
#include "Modio/ModInstallationManagement__ExecuteJobs_d__40.hpp"
#include "Modio/ModInstallationManagement__GetAllInstalledMods_d__36.hpp"
#include "Modio/ModInstallationManagement__Init_d__30.hpp"
#include "Modio/ModInstallationManagement__IsThereAvailableSpaceFor_d__64.hpp"
#include "Modio/ModInstallationManagement__RetryInstallingMod_d__48.hpp"
#include "Modio/ModInstallationManagement__SaveIndex_d__39.hpp"
#include "Modio/ModInstallationManagement__Shutdown_d__31.hpp"
#include "Modio/ModInstallationManagement__StartTempModSession_d__42.hpp"
#include "Modio/ModInstallationManagement__UninstallAllMods_d__65.hpp"
#include "Modio/ModioClient.hpp"
#include "Modio/ModioClient__Init_d__26.hpp"
#include "Modio/ModioClient__Shutdown_d__27.hpp"
#include "Modio/ModioCommandLine.hpp"
#include "Modio/ModioConsoleLog.hpp"
#include "Modio/ModioDebugMenuAttribute.hpp"
#include "Modio/ModioLog.hpp"
#include "Modio/ModioServicePriority.hpp"
#include "Modio/ModioServices.hpp"
#include "Modio/ModioSettings.hpp"
#include "Modio/TermsOfUse.hpp"
#include "Modio/TermsOfUseLink.hpp"
#include "Modio/TermsOfUse__Get_d__17.hpp"
#include "Modio/Version.hpp"
#ifdef __cpp_modules
                    export module Modio;
                    #endif
                
