#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "ICSharpCode/SharpZipLib/Zip/BaseArchiveStorage.hpp"
#include "ICSharpCode/SharpZipLib/Zip/CompressionMethod.hpp"
#include "ICSharpCode/SharpZipLib/Zip/DescriptorData.hpp"
#include "ICSharpCode/SharpZipLib/Zip/DiskArchiveStorage.hpp"
#include "ICSharpCode/SharpZipLib/Zip/DynamicDiskDataSource.hpp"
#include "ICSharpCode/SharpZipLib/Zip/EncryptionAlgorithm.hpp"
#include "ICSharpCode/SharpZipLib/Zip/EntryPatchData.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ExtendedUnixData.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ExtendedUnixData_Flags.hpp"
#include "ICSharpCode/SharpZipLib/Zip/FastZip.hpp"
#include "ICSharpCode/SharpZipLib/Zip/FastZipEvents.hpp"
#include "ICSharpCode/SharpZipLib/Zip/FastZip_Overwrite.hpp"
#include "ICSharpCode/SharpZipLib/Zip/FileUpdateMode.hpp"
#include "ICSharpCode/SharpZipLib/Zip/GeneralBitFlags.hpp"
#include "ICSharpCode/SharpZipLib/Zip/HostSystemID.hpp"
#include "ICSharpCode/SharpZipLib/Zip/IArchiveStorage.hpp"
#include "ICSharpCode/SharpZipLib/Zip/IDynamicDataSource.hpp"
#include "ICSharpCode/SharpZipLib/Zip/IEntryFactory.hpp"
#include "ICSharpCode/SharpZipLib/Zip/IStaticDataSource.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ITaggedData.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ITaggedDataFactory.hpp"
#include "ICSharpCode/SharpZipLib/Zip/KeysRequiredEventArgs.hpp"
#include "ICSharpCode/SharpZipLib/Zip/MemoryArchiveStorage.hpp"
#include "ICSharpCode/SharpZipLib/Zip/NTTaggedData.hpp"
#include "ICSharpCode/SharpZipLib/Zip/PathTransformer.hpp"
#include "ICSharpCode/SharpZipLib/Zip/RawTaggedData.hpp"
#include "ICSharpCode/SharpZipLib/Zip/StaticDiskDataSource.hpp"
#include "ICSharpCode/SharpZipLib/Zip/TestOperation.hpp"
#include "ICSharpCode/SharpZipLib/Zip/TestStatus.hpp"
#include "ICSharpCode/SharpZipLib/Zip/TestStrategy.hpp"
#include "ICSharpCode/SharpZipLib/Zip/UseZip64.hpp"
#include "ICSharpCode/SharpZipLib/Zip/WindowsNameTransform.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipConstants.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipEncryptionMethod.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipEntry.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipEntryExtensions.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipEntryFactory.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipEntryFactory_TimeSetting.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipEntry_Known.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipException.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipExtraData.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipFile.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipFile_HeaderTest.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipFile_UpdateCommand.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipHelperStream.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipInputStream.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipNameTransform.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipOutputStream.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipStrings.hpp"
#include "ICSharpCode/SharpZipLib/Zip/ZipTestResultHandler.hpp"
#ifdef __cpp_modules
                    export module Zip;
                    #endif
                
