#pragma once
// IWYU pragma: begin_exports
#include "UnityEngine/AddressableAssets/ResourceLocators/zzzz__ContentCatalogData_AssetBundleRequestOptionsSerializationAdapter_SerializedData_Common_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "UnityEngine/AddressableAssets/ResourceLocators/zzzz__ContentCatalogData_AssetBundleRequestOptionsSerializationAdapter_SerializedData_Common_impl.hpp"
#endif
// IWYU pragma: end_exports
