#pragma once
// IWYU pragma private; include "UnityEngine/PlayerLoop/EarlyUpdate.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_ARCoreUpdate_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_AnalyticsCoreStatsUpdate_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_ClearIntermediateRenderers_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_ClearLines_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_DeliverIosPlatformEvents_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_DispatchEventQueueEvents_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_ExecuteMainThreadJobs_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_GpuTimestamp_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_InsightsUpdate_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_PerformanceAnalyticsUpdate_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_Physics2DEarlyUpdate_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_PhysicsResetInterpolatedTransformPosition_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_PlayerCleanupCachedData_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_PollHtcsPlayerConnection_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_PollPlayerConnection_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_PresentBeforeUpdate_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_ProcessMouseInWindow_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_ProcessRemoteInput_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_RendererNotifyInvisible_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_ResetFrameStatsAfterPresent_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_ScriptRunDelayedStartupFrame_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_SpriteAtlasManagerUpdate_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_TangoUpdate_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_UnityWebRequestUpdate_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_UpdateAsyncInstantiate_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_UpdateAsyncReadbackManager_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_UpdateCanvasRectTransform_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_UpdateContentLoading_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_UpdateInputManager_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_UpdateKinect_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_UpdateMainGameViewRect_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_UpdatePreloading_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_UpdateStreamingManager_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_UpdateTextureStreamingManager_def.hpp"
#include "UnityEngine/PlayerLoop/zzzz__EarlyUpdate_XRUpdate_def.hpp"
// Ctor Parameters []
constexpr ::UnityEngine::PlayerLoop::EarlyUpdate::EarlyUpdate()   {
}
