#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Photon/Pun/ConnectMethod.hpp"
#include "Photon/Pun/CustomTypes.hpp"
#include "Photon/Pun/DefaultPool.hpp"
#include "Photon/Pun/IOnPhotonViewControllerChange.hpp"
#include "Photon/Pun/IOnPhotonViewOwnerChange.hpp"
#include "Photon/Pun/IOnPhotonViewPreNetDestroy.hpp"
#include "Photon/Pun/IPhotonViewCallback.hpp"
#include "Photon/Pun/IPunInstantiateMagicCallback.hpp"
#include "Photon/Pun/IPunObservable.hpp"
#include "Photon/Pun/IPunOwnershipCallbacks.hpp"
#include "Photon/Pun/IPunPrefabPool.hpp"
#include "Photon/Pun/IPunPrefabPoolVerify.hpp"
#include "Photon/Pun/InstantiateParameters.hpp"
#include "Photon/Pun/MonoBehaviourPun.hpp"
#include "Photon/Pun/MonoBehaviourPunCallbacks.hpp"
#include "Photon/Pun/NestedComponentUtilities.hpp"
#include "Photon/Pun/OwnershipOption.hpp"
#include "Photon/Pun/PhotonAnimatorView.hpp"
#include "Photon/Pun/PhotonAnimatorView_ParameterType.hpp"
#include "Photon/Pun/PhotonAnimatorView_SynchronizeType.hpp"
#include "Photon/Pun/PhotonHandler.hpp"
#include "Photon/Pun/PhotonMessageInfo.hpp"
#include "Photon/Pun/PhotonNetwork.hpp"
#include "Photon/Pun/PhotonNetwork_RaiseEventBatch.hpp"
#include "Photon/Pun/PhotonRigidbody2DView.hpp"
#include "Photon/Pun/PhotonRigidbodyView.hpp"
#include "Photon/Pun/PhotonStream.hpp"
#include "Photon/Pun/PhotonStreamQueue.hpp"
#include "Photon/Pun/PhotonTransformView.hpp"
#include "Photon/Pun/PhotonTransformViewClassic.hpp"
#include "Photon/Pun/PhotonTransformViewPositionControl.hpp"
#include "Photon/Pun/PhotonTransformViewPositionModel.hpp"
#include "Photon/Pun/PhotonTransformViewPositionModel_ExtrapolateOptions.hpp"
#include "Photon/Pun/PhotonTransformViewPositionModel_InterpolateOptions.hpp"
#include "Photon/Pun/PhotonTransformViewRotationControl.hpp"
#include "Photon/Pun/PhotonTransformViewRotationModel.hpp"
#include "Photon/Pun/PhotonTransformViewRotationModel_InterpolateOptions.hpp"
#include "Photon/Pun/PhotonTransformViewScaleControl.hpp"
#include "Photon/Pun/PhotonTransformViewScaleModel.hpp"
#include "Photon/Pun/PhotonTransformViewScaleModel_InterpolateOptions.hpp"
#include "Photon/Pun/PhotonView.hpp"
#include "Photon/Pun/PhotonView_CallbackTargetChange.hpp"
#include "Photon/Pun/PhotonView_ObservableSearch.hpp"
#include "Photon/Pun/PunEvent.hpp"
#include "Photon/Pun/PunExtensions.hpp"
#include "Photon/Pun/PunLogLevel.hpp"
#include "Photon/Pun/PunRPC.hpp"
#include "Photon/Pun/RigOwnedRigidbodyView.hpp"
#include "Photon/Pun/RigOwnedTransformView.hpp"
#include "Photon/Pun/RpcTarget.hpp"
#include "Photon/Pun/SceneManagerHelper.hpp"
#include "Photon/Pun/ServerSettings.hpp"
#include "Photon/Pun/ViewSynchronization.hpp"
#ifdef __cpp_modules
                    export module Pun;
                    #endif
                
