#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Meta/WitAi/ArrayNodeReference.hpp"
#include "Meta/WitAi/ArrayPool_1.hpp"
#include "Meta/WitAi/AudioDurationTracker.hpp"
#include "Meta/WitAi/BaseSpeechService.hpp"
#include "Meta/WitAi/Comment.hpp"
#include "Meta/WitAi/ComponentExtensions.hpp"
#include "Meta/WitAi/ComponentExtensions_ComponentCopyData.hpp"
#include "Meta/WitAi/CoroutineUtility.hpp"
#include "Meta/WitAi/EnumerableExtensions.hpp"
#include "Meta/WitAi/ITelemetryEventsProvider.hpp"
#include "Meta/WitAi/IVoiceActivationHandler.hpp"
#include "Meta/WitAi/IVoiceEventProvider.hpp"
#include "Meta/WitAi/IVoiceService.hpp"
#include "Meta/WitAi/IWitRequestConfiguration.hpp"
#include "Meta/WitAi/IWitRequestEndpointInfo.hpp"
#include "Meta/WitAi/IWitRuntimeConfigProvider.hpp"
#include "Meta/WitAi/IWitRuntimeConfigSetter.hpp"
#include "Meta/WitAi/MatchIntent.hpp"
#include "Meta/WitAi/MatchIntentRegistry.hpp"
#include "Meta/WitAi/ObjectNodeReference.hpp"
#include "Meta/WitAi/ObjectPool_1.hpp"
#include "Meta/WitAi/RegisteredMatchIntent.hpp"
#include "Meta/WitAi/TTSWitAudioType.hpp"
#include "Meta/WitAi/TaskExtensions.hpp"
#include "Meta/WitAi/TaskUtility.hpp"
#include "Meta/WitAi/TaskUtility__WaitForTimeout_d__3.hpp"
#include "Meta/WitAi/ThreadUtility.hpp"
#include "Meta/WitAi/ThreadUtility__SafeTask_d__13.hpp"
#include "Meta/WitAi/ThreadUtility__SafeTask_d__14_1.hpp"
#include "Meta/WitAi/UnityEventExtensions.hpp"
#include "Meta/WitAi/UnityObjectExtensions.hpp"
#include "Meta/WitAi/VLog.hpp"
#include "Meta/WitAi/VoiceService.hpp"
#include "Meta/WitAi/VoiceService_<>c__DisplayClass39_0___Activate_b__0_d.hpp"
#include "Meta/WitAi/VoiceService__InitializeConduit_d__59.hpp"
#include "Meta/WitAi/Wit.hpp"
#include "Meta/WitAi/WitConstants.hpp"
#include "Meta/WitAi/WitRequest.hpp"
#include "Meta/WitAi/WitRequestFactory.hpp"
#include "Meta/WitAi/WitRequestSettings.hpp"
#include "Meta/WitAi/WitRequestType.hpp"
#include "Meta/WitAi/WitRequest__StartThreadedRequest_d__91.hpp"
#include "Meta/WitAi/WitRequest__WaitForTimeout_d__94.hpp"
#include "Meta/WitAi/WitRequest___HandleSend_b__89_0_d.hpp"
#include "Meta/WitAi/WitResponseReference.hpp"
#include "Meta/WitAi/WitResultUtilities.hpp"
#include "Meta/WitAi/WitService.hpp"
#ifdef __cpp_modules
                    export module WitAi;
                    #endif
                
