#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Meta/XR/MultiplayerBlocks/Shared/AvatarStreamLOD.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/BBPlatformInitStatus.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/ColocationController.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/ColocationDebuggingOptions.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/ColocationSessionEventHandler.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/ColocationSessionEventHandler_Basis.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/ColocationSessionEventHandler_SpaceSharingInfo.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/ColocationSessionEventHandler__LoadScene_d__14.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/ColocationSessionEventHandler__OnSessionCreatedWithSpaceSharing_d__15.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/ColocationSessionEventHandler__OnSessionCreatedWithSpatialAnchor_d__10.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/ColocationSessionEventHandler__OnSessionDiscoveredWithSpaceSharing_d__16.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/ColocationSessionEventHandler__OnSessionDiscoveredWithSpatialAnchor_d__11.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/ColocationSessionEventHandler__RequestScenePermissionIfNeeded_d__13.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/ColocationSessionEventHandler__SpaceSharingBeforeHostStart_d__12.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/CustomMatchmaking.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/CustomMatchmakingUtils.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/CustomMatchmaking_RoomCreationOptions.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/CustomMatchmaking_RoomOperationResult.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/CustomMatchmaking__CreateRoom_d__25.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/CustomMatchmaking__CreateRoom_d__26.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/CustomMatchmaking__JoinOpenRoom_d__28.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/CustomMatchmaking__JoinRoom_d__27.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/FriendsMatchmaking.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/FriendsMatchmaking__JoinRoom_d__25.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/FriendsMatchmaking__OnJoinIntentReceived_d__31.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/FriendsMatchmaking__OnRoomOperationResult_d__24.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/FriendsMatchmaking__RegisterGameRoom_d__27.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/IAvatarBehaviour.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/IAvatarStreamConfig.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/INameTagSpawner.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/ITransferOwnership.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/LocalMatchmaking.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/LocalMatchmaking__HostOrJoinSessionAutomatically_d__16.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/LocalMatchmaking__OnColocationSessionFound_d__18.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/LocalMatchmaking__StartAdvertisingColocationSession_d__19.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/LocalMatchmaking__StartAsGuest_d__15.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/LocalMatchmaking__StartAsHost_d__14.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/LocalMatchmaking__StartDiscoveringColocationSessions_d__21.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/LocalMatchmaking__StopAdvertisingColocationSession_d__20.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/LocalMatchmaking__StopDiscoveringColocationSessions_d__22.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/MatchInfo.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/NetworkBootstrapperParams.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/NetworkBootstrapperUtils.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/PlatformInfo.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/PlatformInit.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/PlatformInit_.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/PlayerNameTagSpawner.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/SerializationUtils.hpp"
#include "Meta/XR/MultiplayerBlocks/Shared/TransferOwnershipOnSelect.hpp"
#ifdef __cpp_modules
                    export module Shared;
                    #endif
                
