#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "BoingKit/Aabb.hpp"
#include "BoingKit/BitArray.hpp"
#include "BoingKit/Bits32.hpp"
#include "BoingKit/BoingBase.hpp"
#include "BoingKit/BoingBehavior.hpp"
#include "BoingKit/BoingBoneCollider.hpp"
#include "BoingKit/BoingBoneCollider_Type.hpp"
#include "BoingKit/BoingBones.hpp"
#include "BoingKit/BoingBones_Chain_CurveType.hpp"
#include "BoingKit/BoingEffector.hpp"
#include "BoingKit/BoingEffector_Params.hpp"
#include "BoingKit/BoingKit.hpp"
#include "BoingKit/BoingManager.hpp"
#include "BoingKit/BoingManagerPostUpdatePump.hpp"
#include "BoingKit/BoingManagerPreUpdatePump.hpp"
#include "BoingKit/BoingManager_TranslationLockSpace.hpp"
#include "BoingKit/BoingManager_UpdateMode.hpp"
#include "BoingKit/BoingReactor.hpp"
#include "BoingKit/BoingReactorField.hpp"
#include "BoingKit/BoingReactorFieldCPUSampler.hpp"
#include "BoingKit/BoingReactorFieldGPUSampler.hpp"
#include "BoingKit/BoingReactorField_CellMoveModeEnum.hpp"
#include "BoingKit/BoingReactorField_FalloffDimensionsEnum.hpp"
#include "BoingKit/BoingReactorField_FalloffModeEnum.hpp"
#include "BoingKit/BoingReactorField_FieldParams.hpp"
#include "BoingKit/BoingReactorField_HardwareModeEnum.hpp"
#include "BoingKit/BoingWork.hpp"
#include "BoingKit/BoingWorkAsynchronous.hpp"
#include "BoingKit/BoingWorkAsynchronous_BehaviorJob.hpp"
#include "BoingKit/BoingWorkAsynchronous_ReactorJob.hpp"
#include "BoingKit/BoingWorkSynchronous.hpp"
#include "BoingKit/BoingWork_EffectorFlags.hpp"
#include "BoingKit/BoingWork_Output.hpp"
#include "BoingKit/BoingWork_Params.hpp"
#include "BoingKit/BoingWork_Params_InstanceData.hpp"
#include "BoingKit/BoingWork_ReactorFlags.hpp"
#include "BoingKit/Codec.hpp"
#include "BoingKit/Codec_IntFloat.hpp"
#include "BoingKit/Collision.hpp"
#include "BoingKit/ConditionalFieldAttribute.hpp"
#include "BoingKit/FloatSpring.hpp"
#include "BoingKit/MathUtil.hpp"
#include "BoingKit/ParameterMode.hpp"
#include "BoingKit/QuaternionSpring.hpp"
#include "BoingKit/QuaternionUtil.hpp"
#include "BoingKit/QuaternionUtil_SterpMode.hpp"
#include "BoingKit/SharedBoingParams.hpp"
#include "BoingKit/TwoDPlaneEnum.hpp"
#include "BoingKit/UFOController.hpp"
#include "BoingKit/Vector2Spring.hpp"
#include "BoingKit/Vector3Spring.hpp"
#include "BoingKit/Vector4Spring.hpp"
#include "BoingKit/VectorUtil.hpp"
#include "BoingKit/Version.hpp"
#ifdef __cpp_modules
                    export module BoingKit;
                    #endif
                
