#pragma once
// IWYU pragma: begin_exports
#include "UnityEngine/Rendering/RenderGraphModule/zzzz__RenderGraph_DebugData_PassData_NRPInfo_NativeRenderPassInfo_PassCompatibilityInfo_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "UnityEngine/Rendering/RenderGraphModule/zzzz__RenderGraph_DebugData_PassData_NRPInfo_NativeRenderPassInfo_PassCompatibilityInfo_impl.hpp"
#endif
// IWYU pragma: end_exports
