#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Technie/PhysicsCreator/AlignedCapsuleFitter.hpp"
#include "Technie/PhysicsCreator/AutoHullPreset.hpp"
#include "Technie/PhysicsCreator/AxisAlignedBoxFitter.hpp"
#include "Technie/PhysicsCreator/BoxDef.hpp"
#include "Technie/PhysicsCreator/BoxFitMethod.hpp"
#include "Technie/PhysicsCreator/CapsuleAxis.hpp"
#include "Technie/PhysicsCreator/CapsuleDef.hpp"
#include "Technie/PhysicsCreator/Console.hpp"
#include "Technie/PhysicsCreator/ConstructionPlane.hpp"
#include "Technie/PhysicsCreator/CuttableMesh.hpp"
#include "Technie/PhysicsCreator/CuttableSubMesh.hpp"
#include "Technie/PhysicsCreator/FaceAlignmentBoxFitter.hpp"
#include "Technie/PhysicsCreator/GizmoUtils.hpp"
#include "Technie/PhysicsCreator/Hash160.hpp"
#include "Technie/PhysicsCreator/HashUtil.hpp"
#include "Technie/PhysicsCreator/HullData.hpp"
#include "Technie/PhysicsCreator/HullMapping.hpp"
#include "Technie/PhysicsCreator/HullType.hpp"
#include "Technie/PhysicsCreator/ICreatorComponent.hpp"
#include "Technie/PhysicsCreator/IEditorData.hpp"
#include "Technie/PhysicsCreator/IHull.hpp"
#include "Technie/PhysicsCreator/MeshCutter.hpp"
#include "Technie/PhysicsCreator/PaintingData.hpp"
#include "Technie/PhysicsCreator/PhysicsCreatorHullFolder.hpp"
#include "Technie/PhysicsCreator/PhysicsCreatorInstallRoot.hpp"
#include "Technie/PhysicsCreator/Pose.hpp"
#include "Technie/PhysicsCreator/QHullUtil.hpp"
#include "Technie/PhysicsCreator/RigidColliderCreator.hpp"
#include "Technie/PhysicsCreator/RigidColliderCreatorChild.hpp"
#include "Technie/PhysicsCreator/RotatedBox.hpp"
#include "Technie/PhysicsCreator/RotatedBoxFitter.hpp"
#include "Technie/PhysicsCreator/RotatedCapsule.hpp"
#include "Technie/PhysicsCreator/RotatedCapsuleFitter.hpp"
#include "Technie/PhysicsCreator/Sphere.hpp"
#include "Technie/PhysicsCreator/SphereFitter.hpp"
#include "Technie/PhysicsCreator/SphereUtils.hpp"
#include "Technie/PhysicsCreator/ToolGUILayout.hpp"
#include "Technie/PhysicsCreator/Triangle.hpp"
#include "Technie/PhysicsCreator/TriangleAreaSorter.hpp"
#include "Technie/PhysicsCreator/TriangleBucket.hpp"
#include "Technie/PhysicsCreator/TriangleBucketSorter.hpp"
#include "Technie/PhysicsCreator/UnpackedMesh.hpp"
#include "Technie/PhysicsCreator/Utils.hpp"
#include "Technie/PhysicsCreator/VertexClassification.hpp"
#include "Technie/PhysicsCreator/VhacdParameters.hpp"
#include "Technie/PhysicsCreator/VolumeSorter.hpp"
#ifdef __cpp_modules
                    export module PhysicsCreator;
                    #endif
                
