#pragma once
// IWYU pragma private; include "Technie/PhysicsCreator/HullMapping.hpp"
#include "System/zzzz__Object_impl.hpp"
#include "Technie/PhysicsCreator/zzzz__RigidColliderCreatorChild_impl.hpp"
#include "UnityEngine/zzzz__MeshCollider_impl.hpp"
#include "Technie/PhysicsCreator/zzzz__HullMapping_def.hpp"
#include "Technie/PhysicsCreator/Rigid/zzzz__Hull_def.hpp"
#include "Technie/PhysicsCreator/zzzz__RigidColliderCreatorChild_def.hpp"
#include "UnityEngine/zzzz__Collider_def.hpp"
#include "UnityEngine/zzzz__MeshCollider_def.hpp"
//  Writing Method size for method: ::Technie::PhysicsCreator::HullMapping.AddAutoChild
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<void (::Technie::PhysicsCreator::HullMapping::*)(::Technie::PhysicsCreator::RigidColliderCreatorChild*, ::UnityEngine::MeshCollider*)>(&::Technie::PhysicsCreator::HullMapping::AddAutoChild)> {
  constexpr static std::size_t size = 0x328;
  constexpr static std::size_t addrs = 0xadce134;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::Technie::PhysicsCreator::HullMapping*>(),
                        {"AddAutoChild", {}, {::i2c::type_of<::Technie::PhysicsCreator::RigidColliderCreatorChild*>(), ::i2c::type_of<::UnityEngine::MeshCollider*>()}}
                    )));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::Technie::PhysicsCreator::HullMapping._ctor
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<void (::Technie::PhysicsCreator::HullMapping::*)()>(&::Technie::PhysicsCreator::HullMapping::_ctor)> {
  constexpr static std::size_t size = 0x8;
  constexpr static std::size_t addrs = 0xadce45c;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::Technie::PhysicsCreator::HullMapping*>(),
                        {".ctor", {}, {}}
                    )));
    return ___internal_method;
  }
};
constexpr ::Technie::PhysicsCreator::Rigid::Hull*& Technie::PhysicsCreator::HullMapping::__cordl_internal_get_sourceHull()  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___sourceHull;
}
constexpr ::Technie::PhysicsCreator::Rigid::Hull* const& Technie::PhysicsCreator::HullMapping::__cordl_internal_get_sourceHull() const {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___sourceHull;
}
constexpr void Technie::PhysicsCreator::HullMapping::__cordl_internal_set_sourceHull(::Technie::PhysicsCreator::Rigid::Hull*  value)  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
this->___sourceHull = value;
}
constexpr ::UnityW<::UnityEngine::Collider>& Technie::PhysicsCreator::HullMapping::__cordl_internal_get_generatedCollider()  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___generatedCollider;
}
constexpr ::UnityW<::UnityEngine::Collider> const& Technie::PhysicsCreator::HullMapping::__cordl_internal_get_generatedCollider() const {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___generatedCollider;
}
constexpr void Technie::PhysicsCreator::HullMapping::__cordl_internal_set_generatedCollider(::UnityW<::UnityEngine::Collider>  value)  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
this->___generatedCollider = value;
}
constexpr ::ArrayW<::UnityW<::UnityEngine::MeshCollider>>& Technie::PhysicsCreator::HullMapping::__cordl_internal_get_autoGeneratedColliders()  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___autoGeneratedColliders;
}
constexpr ::ArrayW<::UnityW<::UnityEngine::MeshCollider>> const& Technie::PhysicsCreator::HullMapping::__cordl_internal_get_autoGeneratedColliders() const {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___autoGeneratedColliders;
}
constexpr void Technie::PhysicsCreator::HullMapping::__cordl_internal_set_autoGeneratedColliders(::ArrayW<::UnityW<::UnityEngine::MeshCollider>>  value)  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
this->___autoGeneratedColliders = value;
}
constexpr ::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>& Technie::PhysicsCreator::HullMapping::__cordl_internal_get_targetChild()  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___targetChild;
}
constexpr ::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild> const& Technie::PhysicsCreator::HullMapping::__cordl_internal_get_targetChild() const {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___targetChild;
}
constexpr void Technie::PhysicsCreator::HullMapping::__cordl_internal_set_targetChild(::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>  value)  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
this->___targetChild = value;
}
constexpr ::ArrayW<::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>>& Technie::PhysicsCreator::HullMapping::__cordl_internal_get_targetAutoGeneratedChilds()  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___targetAutoGeneratedChilds;
}
constexpr ::ArrayW<::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>> const& Technie::PhysicsCreator::HullMapping::__cordl_internal_get_targetAutoGeneratedChilds() const {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___targetAutoGeneratedChilds;
}
constexpr void Technie::PhysicsCreator::HullMapping::__cordl_internal_set_targetAutoGeneratedChilds(::ArrayW<::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>>  value)  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
this->___targetAutoGeneratedChilds = value;
}
inline void Technie::PhysicsCreator::HullMapping::AddAutoChild(::Technie::PhysicsCreator::RigidColliderCreatorChild*  newChild, ::UnityEngine::MeshCollider*  newCollider)  {
static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::Technie::PhysicsCreator::HullMapping*>(),
                        {"AddAutoChild", {}, {::i2c::type_of<::Technie::PhysicsCreator::RigidColliderCreatorChild*>(), ::i2c::type_of<::UnityEngine::MeshCollider*>()}}
                    )));
return ::cordl_internals::RunMethodRethrow<void>(this, ___internal_method, newChild, newCollider);
}
inline void Technie::PhysicsCreator::HullMapping::_ctor()  {
static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::Technie::PhysicsCreator::HullMapping*>(),
                        {".ctor", {}, {}}
                    )));
return ::cordl_internals::RunMethodRethrow<void>(this, ___internal_method);
}
inline ::Technie::PhysicsCreator::HullMapping* Technie::PhysicsCreator::HullMapping::New_ctor()  {
return THROW_UNLESS(::i2c::no_logger{}, ::i2c::new_ctor<::Technie::PhysicsCreator::HullMapping*>());
}
// Ctor Parameters []
constexpr ::Technie::PhysicsCreator::HullMapping::HullMapping()   {
}
