#pragma once
// IWYU pragma private; include "Technie/PhysicsCreator/HullMapping.hpp"
#include "beatsaber-hook/shared/types.hpp"
#include "../../cordl_internals/cordl_internals.hpp"
CORDL_MODULE_INIT
#include "System/zzzz__Object_def.hpp"
#include "Technie/PhysicsCreator/zzzz__RigidColliderCreatorChild_def.hpp"
#include "UnityEngine/zzzz__MeshCollider_def.hpp"
#include "beatsaber-hook/shared/arrayw.hpp"
CORDL_MODULE_EXPORT(HullMapping)
namespace Technie::PhysicsCreator::Rigid {
class Hull;
}
namespace Technie::PhysicsCreator {
class RigidColliderCreatorChild;
}
namespace UnityEngine {
class Collider;
}
namespace UnityEngine {
class MeshCollider;
}
// Forward declare root types
namespace Technie::PhysicsCreator {
class HullMapping;
}
// Write type traits
MARK_REF_T(::Technie::PhysicsCreator::HullMapping*);
DEFINE_IL2CPP_CLASS(::Technie::PhysicsCreator::HullMapping*, "Technie.PhysicsCreator", "HullMapping");
// Dependencies System.Object, Technie.PhysicsCreator.RigidColliderCreatorChild, UnityEngine.MeshCollider
namespace Technie::PhysicsCreator {
// Is value type: false
// CS Name: Technie.PhysicsCreator.HullMapping
class CORDL_TYPE HullMapping : public ::System::Object {
public:
// Declarations
/// @brief Field autoGeneratedColliders, offset 0x20, size 0x8 
 __declspec(property(get=__cordl_internal_get_autoGeneratedColliders, put=__cordl_internal_set_autoGeneratedColliders)) ::ArrayW<::UnityW<::UnityEngine::MeshCollider>>  autoGeneratedColliders;

/// @brief Field generatedCollider, offset 0x18, size 0x8 
 __declspec(property(get=__cordl_internal_get_generatedCollider, put=__cordl_internal_set_generatedCollider)) ::UnityW<::UnityEngine::Collider>  generatedCollider;

/// @brief Field sourceHull, offset 0x10, size 0x8 
 __declspec(property(get=__cordl_internal_get_sourceHull, put=__cordl_internal_set_sourceHull)) ::Technie::PhysicsCreator::Rigid::Hull*  sourceHull;

/// @brief Field targetAutoGeneratedChilds, offset 0x30, size 0x8 
 __declspec(property(get=__cordl_internal_get_targetAutoGeneratedChilds, put=__cordl_internal_set_targetAutoGeneratedChilds)) ::ArrayW<::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>>  targetAutoGeneratedChilds;

/// @brief Field targetChild, offset 0x28, size 0x8 
 __declspec(property(get=__cordl_internal_get_targetChild, put=__cordl_internal_set_targetChild)) ::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>  targetChild;

/// @brief Method AddAutoChild, addr 0xadce134, size 0x328, virtual false, abstract: false, final false
inline void AddAutoChild(::Technie::PhysicsCreator::RigidColliderCreatorChild*  newChild, ::UnityEngine::MeshCollider*  newCollider) ;

static inline ::Technie::PhysicsCreator::HullMapping* New_ctor() ;

constexpr ::ArrayW<::UnityW<::UnityEngine::MeshCollider>> const& __cordl_internal_get_autoGeneratedColliders() const;

constexpr ::ArrayW<::UnityW<::UnityEngine::MeshCollider>>& __cordl_internal_get_autoGeneratedColliders() ;

constexpr ::UnityW<::UnityEngine::Collider> const& __cordl_internal_get_generatedCollider() const;

constexpr ::UnityW<::UnityEngine::Collider>& __cordl_internal_get_generatedCollider() ;

constexpr ::Technie::PhysicsCreator::Rigid::Hull* const& __cordl_internal_get_sourceHull() const;

constexpr ::Technie::PhysicsCreator::Rigid::Hull*& __cordl_internal_get_sourceHull() ;

constexpr ::ArrayW<::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>> const& __cordl_internal_get_targetAutoGeneratedChilds() const;

constexpr ::ArrayW<::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>>& __cordl_internal_get_targetAutoGeneratedChilds() ;

constexpr ::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild> const& __cordl_internal_get_targetChild() const;

constexpr ::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>& __cordl_internal_get_targetChild() ;

constexpr void __cordl_internal_set_autoGeneratedColliders(::ArrayW<::UnityW<::UnityEngine::MeshCollider>>  value) ;

constexpr void __cordl_internal_set_generatedCollider(::UnityW<::UnityEngine::Collider>  value) ;

constexpr void __cordl_internal_set_sourceHull(::Technie::PhysicsCreator::Rigid::Hull*  value) ;

constexpr void __cordl_internal_set_targetAutoGeneratedChilds(::ArrayW<::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>>  value) ;

constexpr void __cordl_internal_set_targetChild(::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>  value) ;

/// @brief Method .ctor, addr 0xadce45c, size 0x8, virtual false, abstract: false, final false
inline void _ctor() ;

protected:
// Ctor Parameters []
// @brief default ctor
constexpr HullMapping() ;
public:

// Ctor Parameters [CppParam { name: "", ty: "HullMapping", modifiers: "&&", def_value: None, comment: None }]
// @brief delete move ctor to prevent accidental deref moves
HullMapping(HullMapping && ) = delete;

// Ctor Parameters [CppParam { name: "", ty: "HullMapping", modifiers: "const&", def_value: None, comment: None }]
// @brief delete copy ctor to prevent accidental deref copies
HullMapping(HullMapping const& ) = delete;

/// @brief IL2CPP Metadata Type Index
static constexpr uint32_t  __IL2CPP_TYPE_DEFINITION_INDEX{30516};

/// @brief Field sourceHull, offset: 0x10, size: 0x8, def value: None
 ::Technie::PhysicsCreator::Rigid::Hull*  ___sourceHull;

/// @brief Field generatedCollider, offset: 0x18, size: 0x8, def value: None
 ::UnityW<::UnityEngine::Collider>  ___generatedCollider;

/// @brief Field autoGeneratedColliders, offset: 0x20, size: 0x8, def value: None
 ::ArrayW<::UnityW<::UnityEngine::MeshCollider>>  ___autoGeneratedColliders;

/// @brief Field targetChild, offset: 0x28, size: 0x8, def value: None
 ::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>  ___targetChild;

/// @brief Field targetAutoGeneratedChilds, offset: 0x30, size: 0x8, def value: None
 ::ArrayW<::UnityW<::Technie::PhysicsCreator::RigidColliderCreatorChild>>  ___targetAutoGeneratedChilds;

static constexpr bool __IL2CPP_IS_VALUE_TYPE = false;
};
// Non member Declarations
static_assert(offsetof(::Technie::PhysicsCreator::HullMapping, ___sourceHull) == 0x10, "Offset mismatch!");

static_assert(offsetof(::Technie::PhysicsCreator::HullMapping, ___generatedCollider) == 0x18, "Offset mismatch!");

static_assert(offsetof(::Technie::PhysicsCreator::HullMapping, ___autoGeneratedColliders) == 0x20, "Offset mismatch!");

static_assert(offsetof(::Technie::PhysicsCreator::HullMapping, ___targetChild) == 0x28, "Offset mismatch!");

static_assert(offsetof(::Technie::PhysicsCreator::HullMapping, ___targetAutoGeneratedChilds) == 0x30, "Offset mismatch!");

static_assert(sizeof(::Technie::PhysicsCreator::HullMapping) == 0x38, "Size mismatch!");

} // namespace end def Technie::PhysicsCreator
