#pragma once
// IWYU pragma private; include "Oculus/Interaction/OptionalAttribute_Flag.hpp"
#include "beatsaber-hook/shared/types.hpp"
#include "../../cordl_internals/cordl_internals.hpp"
CORDL_MODULE_INIT
#include <cstddef>
#include <cstdint>
CORDL_MODULE_EXPORT(OptionalAttribute_Flag)
// Forward declare root types
namespace GlobalNamespace {
struct OptionalAttribute_Flag;
}
// Write type traits
MARK_VAL_T(::GlobalNamespace::OptionalAttribute_Flag);
DEFINE_IL2CPP_CLASS(::GlobalNamespace::OptionalAttribute_Flag, "Oculus.Interaction", "OptionalAttribute/Flag");
// [Flags]
// Dependencies 
namespace GlobalNamespace {
// Is value type: true
// CS Name: Oculus.Interaction.OptionalAttribute/Flag
struct CORDL_TYPE OptionalAttribute_Flag {
public:
// Declarations
using __CORDL_BACKING_ENUM_TYPE = int32_t;

/// @brief Nested struct __OptionalAttribute_Flag_Unwrapped
enum struct __OptionalAttribute_Flag_Unwrapped : int32_t {
__E_None = static_cast<int32_t>(0x0),
__E_AutoGenerated = static_cast<int32_t>(0x1),
__E_DontHide = static_cast<int32_t>(0x2),
__E_Obsolete = static_cast<int32_t>(0x4),
};

/// @brief Conversion into unwrapped enum value
constexpr operator __OptionalAttribute_Flag_Unwrapped () const noexcept {
return static_cast<__OptionalAttribute_Flag_Unwrapped>(this->value__);
}

/// @brief Conversion into unwrapped enum value
constexpr explicit operator int32_t () const noexcept {
return static_cast<int32_t>(this->value__);
}

// Ctor Parameters []
// @brief default ctor
constexpr OptionalAttribute_Flag() ;

// Ctor Parameters [CppParam { name: "value__", ty: "int32_t", modifiers: "", def_value: None, comment: None }]
constexpr OptionalAttribute_Flag(int32_t  value__) noexcept;

/// @brief Field AutoGenerated value: I32(1)
static ::GlobalNamespace::OptionalAttribute_Flag const AutoGenerated;

/// @brief Field DontHide value: I32(2)
static ::GlobalNamespace::OptionalAttribute_Flag const DontHide;

/// @brief Field None value: I32(0)
static ::GlobalNamespace::OptionalAttribute_Flag const None;

/// @brief Field Obsolete value: I32(4)
static ::GlobalNamespace::OptionalAttribute_Flag const Obsolete;

/// @brief IL2CPP Metadata Type Index
static constexpr uint32_t  __IL2CPP_TYPE_DEFINITION_INDEX{15689};

/// @brief The size of the true value type
static constexpr auto  __IL2CPP_VALUE_TYPE_SIZE{0x4};

/// @brief Field value__, offset: 0x0, size: 0x4, def value: None
 int32_t  value__;

static constexpr bool __IL2CPP_IS_VALUE_TYPE = true;
};
// Non member Declarations
static_assert(offsetof(::GlobalNamespace::OptionalAttribute_Flag, value__) == 0x0, "Offset mismatch!");

static_assert(sizeof(::GlobalNamespace::OptionalAttribute_Flag) == 0x4, "Size mismatch!");

} // namespace end def GlobalNamespace
