#pragma once
// IWYU pragma private; include "Oculus/Interaction/OptionalAttribute_Flag.hpp"
#include "Oculus/Interaction/zzzz__OptionalAttribute_Flag_def.hpp"
// Ctor Parameters [CppParam { name: "value__", ty: "int32_t", modifiers: "", def_value: Some("{}"), comment: None }]
constexpr ::GlobalNamespace::OptionalAttribute_Flag::OptionalAttribute_Flag(int32_t  value__) noexcept  {
this->value__ = value__;
}
// Ctor Parameters []
constexpr ::GlobalNamespace::OptionalAttribute_Flag::OptionalAttribute_Flag()   {
}
constexpr ::GlobalNamespace::OptionalAttribute_Flag  GlobalNamespace::OptionalAttribute_Flag::None{static_cast<int32_t>(0x0)};
constexpr ::GlobalNamespace::OptionalAttribute_Flag  GlobalNamespace::OptionalAttribute_Flag::AutoGenerated{static_cast<int32_t>(0x1)};
constexpr ::GlobalNamespace::OptionalAttribute_Flag  GlobalNamespace::OptionalAttribute_Flag::DontHide{static_cast<int32_t>(0x2)};
constexpr ::GlobalNamespace::OptionalAttribute_Flag  GlobalNamespace::OptionalAttribute_Flag::Obsolete{static_cast<int32_t>(0x4)};
