#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Fusion/CodeGen/FixedStorage@1.hpp"
#include "Fusion/CodeGen/FixedStorage@10.hpp"
#include "Fusion/CodeGen/FixedStorage@10__Data_e__FixedBuffer.hpp"
#include "Fusion/CodeGen/FixedStorage@129.hpp"
#include "Fusion/CodeGen/FixedStorage@129__Data_e__FixedBuffer.hpp"
#include "Fusion/CodeGen/FixedStorage@153.hpp"
#include "Fusion/CodeGen/FixedStorage@153__Data_e__FixedBuffer.hpp"
#include "Fusion/CodeGen/FixedStorage@18.hpp"
#include "Fusion/CodeGen/FixedStorage@183.hpp"
#include "Fusion/CodeGen/FixedStorage@183__Data_e__FixedBuffer.hpp"
#include "Fusion/CodeGen/FixedStorage@18__Data_e__FixedBuffer.hpp"
#include "Fusion/CodeGen/FixedStorage@1__Data_e__FixedBuffer.hpp"
#include "Fusion/CodeGen/FixedStorage@20.hpp"
#include "Fusion/CodeGen/FixedStorage@207.hpp"
#include "Fusion/CodeGen/FixedStorage@207__Data_e__FixedBuffer.hpp"
#include "Fusion/CodeGen/FixedStorage@20__Data_e__FixedBuffer.hpp"
#include "Fusion/CodeGen/FixedStorage@3.hpp"
#include "Fusion/CodeGen/FixedStorage@33.hpp"
#include "Fusion/CodeGen/FixedStorage@33__Data_e__FixedBuffer.hpp"
#include "Fusion/CodeGen/FixedStorage@3__Data_e__FixedBuffer.hpp"
#include "Fusion/CodeGen/FixedStorage@4.hpp"
#include "Fusion/CodeGen/FixedStorage@4__Data_e__FixedBuffer.hpp"
#include "Fusion/CodeGen/FixedStorage@6.hpp"
#include "Fusion/CodeGen/FixedStorage@6__Data_e__FixedBuffer.hpp"
#include "Fusion/CodeGen/FixedStorage@71.hpp"
#include "Fusion/CodeGen/FixedStorage@71__Data_e__FixedBuffer.hpp"
#include "Fusion/CodeGen/ReaderWriter@BarrelCannon__BarrelCannonState.hpp"
#include "Fusion/CodeGen/ReaderWriter@BatteryChargerState__FusionCrankData.hpp"
#include "Fusion/CodeGen/ReaderWriter@Fusion_NetworkString_1_Fusion__128_.hpp"
#include "Fusion/CodeGen/ReaderWriter@Fusion_NetworkString_1_Fusion__32_.hpp"
#include "Fusion/CodeGen/ReaderWriter@GorillaPaintbrawlManager__PaintbrawlStatus.hpp"
#include "Fusion/CodeGen/ReaderWriter@Meta_XR_MultiplayerBlocks_Colocation_Fusion_FusionAnchor.hpp"
#include "Fusion/CodeGen/ReaderWriter@Meta_XR_MultiplayerBlocks_Colocation_Fusion_FusionPlayer.hpp"
#include "Fusion/CodeGen/ReaderWriter@UnityEngine_Quaternion.hpp"
#include "Fusion/CodeGen/UnityArraySurrogate@ElementReaderWriterBoolean.hpp"
#include "Fusion/CodeGen/UnityArraySurrogate@ElementReaderWriterInt32.hpp"
#include "Fusion/CodeGen/UnityArraySurrogate@ElementReaderWriterInt64.hpp"
#include "Fusion/CodeGen/UnityArraySurrogate@ElementReaderWriterNetworkBool.hpp"
#include "Fusion/CodeGen/UnityArraySurrogate@ElementReaderWriterSingle.hpp"
#include "Fusion/CodeGen/UnityArraySurrogate@ReaderWriter@GorillaPaintbrawlManager__PaintbrawlStatus.hpp"
#include "Fusion/CodeGen/UnityDictionarySurrogate@ElementReaderWriterInt32@ElementReaderWriterInt32.hpp"
#include "Fusion/CodeGen/UnityDictionarySurrogate@ReaderWriter@Fusion_NetworkString_1_Fusion__32_@ReaderWriter@Fusion_NetworkString_1_Fusion__32_.hpp"
#include "Fusion/CodeGen/UnityLinkedListSurrogate@ElementReaderWriterByte.hpp"
#include "Fusion/CodeGen/UnityLinkedListSurrogate@ElementReaderWriterInt32.hpp"
#include "Fusion/CodeGen/UnityLinkedListSurrogate@ElementReaderWriterSingle.hpp"
#include "Fusion/CodeGen/UnityLinkedListSurrogate@ElementReaderWriterVector3.hpp"
#include "Fusion/CodeGen/UnityLinkedListSurrogate@ReaderWriter@UnityEngine_Quaternion.hpp"
#include "Fusion/CodeGen/UnityValueSurrogate@ElementReaderWriterInt32.hpp"
#include "Fusion/CodeGen/UnityValueSurrogate@ElementReaderWriterNetworkBool.hpp"
#include "Fusion/CodeGen/UnityValueSurrogate@ElementReaderWriterSingle.hpp"
#include "Fusion/CodeGen/UnityValueSurrogate@ElementReaderWriterVector3.hpp"
#include "Fusion/CodeGen/UnityValueSurrogate@ReaderWriter@BarrelCannon__BarrelCannonState.hpp"
#include "Fusion/CodeGen/UnityValueSurrogate@ReaderWriter@Fusion_NetworkString_1_Fusion__128_.hpp"
#include "Fusion/CodeGen/UnityValueSurrogate@ReaderWriter@Fusion_NetworkString_1_Fusion__32_.hpp"
#include "Fusion/CodeGen/UnityValueSurrogate@ReaderWriter@UnityEngine_Quaternion.hpp"
#ifdef __cpp_modules
                    export module CodeGen;
                    #endif
                
