#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/IXRActivateInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/IXRGroupMember.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/IXRHoverInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/IXRInteractionGroup.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/IXRInteractionOverrideGroup.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/IXRInteractionStrengthInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/IXRInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/IXRRayProvider.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/IXRScaleValueProvider.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/IXRSelectInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/IXRTargetPriorityInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/InteractorHandedness.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/NearFarInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/NearFarInteractor_NearCasterSortingStrategy.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/NearFarInteractor_Region.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/ScaleMode.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/SocketScaleMode.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/TargetPriorityMode.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRBaseInputInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRBaseInputInteractor_InputCompatibilityMode.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRBaseInputInteractor_InputTriggerType.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRBaseInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRDirectInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRGazeInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRGazeInteractor_GazeAssistanceCalculation.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRGroupMemberExtensions.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRHoverInteractorExtensions.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRInteractionGroup.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRInteractorExtensions.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRPokeInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRPokeInteractor_PokeCollision.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRRayInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRRayInteractor_AnchorRotationMode.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRRayInteractor_HitDetectionType.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRRayInteractor_LineType.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRRayInteractor_QuerySnapVolumeInteraction.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRRayInteractor_RotateMode.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRRayInteractor_SamplePoint.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRSelectInteractorExtensions.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRSocketInteractor.hpp"
#include "UnityEngine/XR/Interaction/Toolkit/Interactors/XRSocketInteractor_ShaderPropertyLookup.hpp"
#ifdef __cpp_modules
                    export module Interactors;
                    #endif
                
