#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "PlayFab/GroupsModels/AcceptGroupApplicationRequest.hpp"
#include "PlayFab/GroupsModels/AcceptGroupInvitationRequest.hpp"
#include "PlayFab/GroupsModels/AddMembersRequest.hpp"
#include "PlayFab/GroupsModels/ApplyToGroupRequest.hpp"
#include "PlayFab/GroupsModels/ApplyToGroupResponse.hpp"
#include "PlayFab/GroupsModels/BlockEntityRequest.hpp"
#include "PlayFab/GroupsModels/ChangeMemberRoleRequest.hpp"
#include "PlayFab/GroupsModels/CreateGroupRequest.hpp"
#include "PlayFab/GroupsModels/CreateGroupResponse.hpp"
#include "PlayFab/GroupsModels/CreateGroupRoleRequest.hpp"
#include "PlayFab/GroupsModels/CreateGroupRoleResponse.hpp"
#include "PlayFab/GroupsModels/DeleteGroupRequest.hpp"
#include "PlayFab/GroupsModels/DeleteRoleRequest.hpp"
#include "PlayFab/GroupsModels/EmptyResponse.hpp"
#include "PlayFab/GroupsModels/EntityKey.hpp"
#include "PlayFab/GroupsModels/EntityMemberRole.hpp"
#include "PlayFab/GroupsModels/EntityWithLineage.hpp"
#include "PlayFab/GroupsModels/GetGroupRequest.hpp"
#include "PlayFab/GroupsModels/GetGroupResponse.hpp"
#include "PlayFab/GroupsModels/GroupApplication.hpp"
#include "PlayFab/GroupsModels/GroupBlock.hpp"
#include "PlayFab/GroupsModels/GroupInvitation.hpp"
#include "PlayFab/GroupsModels/GroupRole.hpp"
#include "PlayFab/GroupsModels/GroupWithRoles.hpp"
#include "PlayFab/GroupsModels/InviteToGroupRequest.hpp"
#include "PlayFab/GroupsModels/InviteToGroupResponse.hpp"
#include "PlayFab/GroupsModels/IsMemberRequest.hpp"
#include "PlayFab/GroupsModels/IsMemberResponse.hpp"
#include "PlayFab/GroupsModels/ListGroupApplicationsRequest.hpp"
#include "PlayFab/GroupsModels/ListGroupApplicationsResponse.hpp"
#include "PlayFab/GroupsModels/ListGroupBlocksRequest.hpp"
#include "PlayFab/GroupsModels/ListGroupBlocksResponse.hpp"
#include "PlayFab/GroupsModels/ListGroupInvitationsRequest.hpp"
#include "PlayFab/GroupsModels/ListGroupInvitationsResponse.hpp"
#include "PlayFab/GroupsModels/ListGroupMembersRequest.hpp"
#include "PlayFab/GroupsModels/ListGroupMembersResponse.hpp"
#include "PlayFab/GroupsModels/ListMembershipOpportunitiesRequest.hpp"
#include "PlayFab/GroupsModels/ListMembershipOpportunitiesResponse.hpp"
#include "PlayFab/GroupsModels/ListMembershipRequest.hpp"
#include "PlayFab/GroupsModels/ListMembershipResponse.hpp"
#include "PlayFab/GroupsModels/OperationTypes.hpp"
#include "PlayFab/GroupsModels/RemoveGroupApplicationRequest.hpp"
#include "PlayFab/GroupsModels/RemoveGroupInvitationRequest.hpp"
#include "PlayFab/GroupsModels/RemoveMembersRequest.hpp"
#include "PlayFab/GroupsModels/UnblockEntityRequest.hpp"
#include "PlayFab/GroupsModels/UpdateGroupRequest.hpp"
#include "PlayFab/GroupsModels/UpdateGroupResponse.hpp"
#include "PlayFab/GroupsModels/UpdateGroupRoleRequest.hpp"
#include "PlayFab/GroupsModels/UpdateGroupRoleResponse.hpp"
#ifdef __cpp_modules
                    export module GroupsModels;
                    #endif
                
