#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Oculus/Interaction/Locomotion/AdjustableAudio.hpp"
#include "Oculus/Interaction/Locomotion/AnimatedSnapTurnVisuals.hpp"
#include "Oculus/Interaction/Locomotion/CapsuleLocomotionHandler.hpp"
#include "Oculus/Interaction/Locomotion/CharacterController.hpp"
#include "Oculus/Interaction/Locomotion/FirstPersonLocomotor.hpp"
#include "Oculus/Interaction/Locomotion/FlyingLocomotor.hpp"
#include "Oculus/Interaction/Locomotion/ILocomotionEventBroadcaster.hpp"
#include "Oculus/Interaction/Locomotion/ILocomotionEventHandler.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionActionsBroadcaster.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionActionsBroadcaster_LocomotionAction.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionActiveState.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionAxisTurnerInteractable.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionAxisTurnerInteractor.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionComfortVignetteSetting.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionComfortVignetteSetting_ComfortType.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionEvent.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionEvent_RotationType.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionEvent_TranslationType.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionEventsConnection.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionGate.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionGateUnityEventWrapper.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionGate_LocomotionMode.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionGate_LocomotionModeEventArgs.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionSeatedSetting.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionTunneling.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionTurnSliderSetting.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionTurnerInteractable.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionTurnerInteractor.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionTurnerInteractorEventsWrapper.hpp"
#include "Oculus/Interaction/Locomotion/LocomotionTurnerInteractorVisual.hpp"
#include "Oculus/Interaction/Locomotion/LocomotorSound.hpp"
#include "Oculus/Interaction/Locomotion/MenuToggler.hpp"
#include "Oculus/Interaction/Locomotion/PlayerLocomotor.hpp"
#include "Oculus/Interaction/Locomotion/SlideLocomotionBroadcaster.hpp"
#include "Oculus/Interaction/Locomotion/StepLocomotionBroadcaster.hpp"
#include "Oculus/Interaction/Locomotion/TeleportArcGravity.hpp"
#include "Oculus/Interaction/Locomotion/TeleportArcVisual.hpp"
#include "Oculus/Interaction/Locomotion/TeleportCandidateComputer.hpp"
#include "Oculus/Interaction/Locomotion/TeleportCandidateComputer___c__DisplayClass10_0.hpp"
#include "Oculus/Interaction/Locomotion/TeleportHit.hpp"
#include "Oculus/Interaction/Locomotion/TeleportInteractable.hpp"
#include "Oculus/Interaction/Locomotion/TeleportInteractor.hpp"
#include "Oculus/Interaction/Locomotion/TeleportProceduralArcVisual.hpp"
#include "Oculus/Interaction/Locomotion/TurnArrowVisuals.hpp"
#include "Oculus/Interaction/Locomotion/TurnLocomotionBroadcaster.hpp"
#include "Oculus/Interaction/Locomotion/TurnerEventBroadcaster.hpp"
#include "Oculus/Interaction/Locomotion/TurnerEventBroadcaster_TurnMode.hpp"
#include "Oculus/Interaction/Locomotion/VirtualActiveState.hpp"
#include "Oculus/Interaction/Locomotion/WallPenetrationTunneling.hpp"
#include "Oculus/Interaction/Locomotion/WristAngleActiveState.hpp"
#ifdef __cpp_modules
                    export module Locomotion;
                    #endif
                
