#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Unity/XR/CoreUtils/ARTrackablesParentTransformChangedEventArgs.hpp"
#include "Unity/XR/CoreUtils/BoolUnityEvent.hpp"
#include "Unity/XR/CoreUtils/BoundsExtensions.hpp"
#include "Unity/XR/CoreUtils/BoundsUtils.hpp"
#include "Unity/XR/CoreUtils/CachedComponentFilter_2.hpp"
#include "Unity/XR/CoreUtils/CachedSearchType.hpp"
#include "Unity/XR/CoreUtils/CameraExtensions.hpp"
#include "Unity/XR/CoreUtils/CollectionExtensions.hpp"
#include "Unity/XR/CoreUtils/CollectionPool_2.hpp"
#include "Unity/XR/CoreUtils/ColorUnityEvent.hpp"
#include "Unity/XR/CoreUtils/ComponentUtils.hpp"
#include "Unity/XR/CoreUtils/ComponentUtils_1.hpp"
#include "Unity/XR/CoreUtils/DictionaryExtensions.hpp"
#include "Unity/XR/CoreUtils/EnumValues_1.hpp"
#include "Unity/XR/CoreUtils/FloatUnityEvent.hpp"
#include "Unity/XR/CoreUtils/GameObjectExtensions.hpp"
#include "Unity/XR/CoreUtils/GameObjectUtils.hpp"
#include "Unity/XR/CoreUtils/GeometryUtils.hpp"
#include "Unity/XR/CoreUtils/GuidExtensions.hpp"
#include "Unity/XR/CoreUtils/GuidUtil.hpp"
#include "Unity/XR/CoreUtils/HashCodeUtil.hpp"
#include "Unity/XR/CoreUtils/HashSetExtensions.hpp"
#include "Unity/XR/CoreUtils/IComponentHost_1.hpp"
#include "Unity/XR/CoreUtils/IntUnityEvent.hpp"
#include "Unity/XR/CoreUtils/LayerMaskExtensions.hpp"
#include "Unity/XR/CoreUtils/ListExtensions.hpp"
#include "Unity/XR/CoreUtils/MaterialUtils.hpp"
#include "Unity/XR/CoreUtils/MathUtility.hpp"
#include "Unity/XR/CoreUtils/MonoBehaviourExtensions.hpp"
#include "Unity/XR/CoreUtils/NativeArrayUtils.hpp"
#include "Unity/XR/CoreUtils/ObjectPool_1.hpp"
#include "Unity/XR/CoreUtils/OnDestroyNotifier.hpp"
#include "Unity/XR/CoreUtils/PoseExtensions.hpp"
#include "Unity/XR/CoreUtils/QuaternionExtensions.hpp"
#include "Unity/XR/CoreUtils/QuaternionUnityEvent.hpp"
#include "Unity/XR/CoreUtils/ReadOnlyAttribute.hpp"
#include "Unity/XR/CoreUtils/ReflectionUtils.hpp"
#include "Unity/XR/CoreUtils/ScriptableSettingsBase.hpp"
#include "Unity/XR/CoreUtils/ScriptableSettingsBase_1.hpp"
#include "Unity/XR/CoreUtils/ScriptableSettingsPathAttribute.hpp"
#include "Unity/XR/CoreUtils/ScriptableSettings_1.hpp"
#include "Unity/XR/CoreUtils/SerializableGuid.hpp"
#include "Unity/XR/CoreUtils/SerializableGuidUtil.hpp"
#include "Unity/XR/CoreUtils/StopwatchExtensions.hpp"
#include "Unity/XR/CoreUtils/StringExtensions.hpp"
#include "Unity/XR/CoreUtils/StringUnityEvent.hpp"
#include "Unity/XR/CoreUtils/TextureUtils.hpp"
#include "Unity/XR/CoreUtils/TransformExtensions.hpp"
#include "Unity/XR/CoreUtils/TypeExtensions.hpp"
#include "Unity/XR/CoreUtils/UndoBlock.hpp"
#include "Unity/XR/CoreUtils/UnityObjectUtils.hpp"
#include "Unity/XR/CoreUtils/Vector2Extensions.hpp"
#include "Unity/XR/CoreUtils/Vector2UnityEvent.hpp"
#include "Unity/XR/CoreUtils/Vector3Extensions.hpp"
#include "Unity/XR/CoreUtils/Vector3UnityEvent.hpp"
#include "Unity/XR/CoreUtils/Vector4UnityEvent.hpp"
#include "Unity/XR/CoreUtils/XRLoggingUtils.hpp"
#include "Unity/XR/CoreUtils/XROrigin.hpp"
#include "Unity/XR/CoreUtils/XROrigin_TrackingOriginMode.hpp"
#ifdef __cpp_modules
                    export module CoreUtils;
                    #endif
                
