#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "PlayFab/IPlayFabPlugin.hpp"
#include "PlayFab/ISerializerPlugin.hpp"
#include "PlayFab/ITransportPlugin.hpp"
#include "PlayFab/PlayFabApiSettings.hpp"
#include "PlayFab/PlayFabAuthenticationAPI.hpp"
#include "PlayFab/PlayFabAuthenticationContext.hpp"
#include "PlayFab/PlayFabAuthenticationInstanceAPI.hpp"
#include "PlayFab/PlayFabClientAPI.hpp"
#include "PlayFab/PlayFabClientInstanceAPI.hpp"
#include "PlayFab/PlayFabCloudScriptAPI.hpp"
#include "PlayFab/PlayFabCloudScriptInstanceAPI.hpp"
#include "PlayFab/PlayFabDataAPI.hpp"
#include "PlayFab/PlayFabDataGatherer.hpp"
#include "PlayFab/PlayFabDataInstanceAPI.hpp"
#include "PlayFab/PlayFabError.hpp"
#include "PlayFab/PlayFabErrorCode.hpp"
#include "PlayFab/PlayFabEventsAPI.hpp"
#include "PlayFab/PlayFabEventsInstanceAPI.hpp"
#include "PlayFab/PlayFabException.hpp"
#include "PlayFab/PlayFabExceptionCode.hpp"
#include "PlayFab/PlayFabExperimentationAPI.hpp"
#include "PlayFab/PlayFabExperimentationInstanceAPI.hpp"
#include "PlayFab/PlayFabGroupsAPI.hpp"
#include "PlayFab/PlayFabGroupsInstanceAPI.hpp"
#include "PlayFab/PlayFabInsightsAPI.hpp"
#include "PlayFab/PlayFabInsightsInstanceAPI.hpp"
#include "PlayFab/PlayFabLocalizationAPI.hpp"
#include "PlayFab/PlayFabLocalizationInstanceAPI.hpp"
#include "PlayFab/PlayFabLogLevel.hpp"
#include "PlayFab/PlayFabMultiplayerAPI.hpp"
#include "PlayFab/PlayFabMultiplayerInstanceAPI.hpp"
#include "PlayFab/PlayFabProfilesAPI.hpp"
#include "PlayFab/PlayFabProfilesInstanceAPI.hpp"
#include "PlayFab/PlayFabSettings.hpp"
#include "PlayFab/PlayFabSettingsRedirect.hpp"
#include "PlayFab/PluginContract.hpp"
#include "PlayFab/PluginContractKey.hpp"
#include "PlayFab/PluginContractKeyComparator.hpp"
#include "PlayFab/PluginManager.hpp"
#include "PlayFab/WebRequestType.hpp"
#include "PlayFab/WsaReflectionExtensions.hpp"
#ifdef __cpp_modules
                    export module PlayFab;
                    #endif
                
