#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Cysharp/Text/EnumUtil_1.hpp"
#include "Cysharp/Text/ExceptionUtil.hpp"
#include "Cysharp/Text/FastNumberWriter.hpp"
#include "Cysharp/Text/FormatParser.hpp"
#include "Cysharp/Text/FormatParser_ParseResult.hpp"
#include "Cysharp/Text/IResettableBufferWriter_1.hpp"
#include "Cysharp/Text/NestedStringBuilderCreationException.hpp"
#include "Cysharp/Text/ParserScanResult.hpp"
#include "Cysharp/Text/PreparedFormatHelper.hpp"
#include "Cysharp/Text/ReadOnlyListAdaptor_1.hpp"
#include "Cysharp/Text/TextMeshProExtensions.hpp"
#include "Cysharp/Text/Utf16FormatHelper.hpp"
#include "Cysharp/Text/Utf16FormatSegment.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_1.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_10.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_11.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_12.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_13.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_14.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_15.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_16.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_2.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_3.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_4.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_5.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_6.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_7.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_8.hpp"
#include "Cysharp/Text/Utf16PreparedFormat_9.hpp"
#include "Cysharp/Text/Utf16ValueStringBuilder.hpp"
#include "Cysharp/Text/Utf8FormatHelper.hpp"
#include "Cysharp/Text/Utf8FormatSegment.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_1.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_10.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_11.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_12.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_13.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_14.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_15.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_16.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_2.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_3.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_4.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_5.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_6.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_7.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_8.hpp"
#include "Cysharp/Text/Utf8PreparedFormat_9.hpp"
#include "Cysharp/Text/Utf8ValueStringBuilder.hpp"
#include "Cysharp/Text/ZString.hpp"
#include "Cysharp/Text/ZStringWriter.hpp"
#ifdef __cpp_modules
                    export module Text;
                    #endif
                
